import Head from 'next/head';
import { Kanit, Roboto } from 'next/font/google';
import LeftTab from '~/components/LeftTab';
import Hero from '~/components/Hero';
import Card from '~/components/Card';
import { api } from '~/utils/api';
import FullSubscribe from '~/components/FullSubscribe';

const roboto = Roboto({
  subsets: ['latin'],
  weight: '400',
  variable: '--roboto-font'
});

const kanit = Kanit({
  subsets: ['latin'],
  weight: '400',
  variable: '--kanit-font'
});

const Home = ({ menuOpen }: { menuOpen: boolean }) => {
  const { data } = api.summaries.getPreview.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${kanit.variable} ${roboto.variable} bg-base100`}>
        <div className="flex h-[calc(100vh-_82.67px)]">
          <LeftTab menuOpen={menuOpen} />
          <div className="grid items-start px-2 pt-10 sm:py-10">
            <Hero />
            <div className="bg-base100 py-16 font-kanit xl:py-40">
              <h1 className="bg-gradient-to-t from-[#5F0A87] to-[#A4508B] bg-clip-text text-center text-3xl font-bold text-transparent sm:text-4xl md:text-5xl">
                LATEST SUMMARIES
              </h1>

              <div className="grid-list grid-template-columns-sm  md:grid-template-columns-md lg:grid-template-columns-lg justify-items-center gap-16 bg-base100 p-6">
                {data?.map((article) => (
                  <Card
                    background={article.category.background}
                    category={article.category.name}
                    description={article.description}
                    title={article.title}
                    image={article.image}
                    id={article.id}
                    key={article.id}
                  />
                ))}
              </div>
            </div>
            <div id="subscribe" className="-mx-2">
              <FullSubscribe />
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
