import { type NextPage } from "next";
import Head from "next/head";
import Nav from "~/components/Nav";
import { Kanit, Roboto } from "next/font/google";
import LeftTab from "~/components/LeftTab";
import { useState } from "react";
import NewsTab from "~/components/NewsTab";
import Hero from "~/components/Hero";

const roboto = Roboto({
  subsets: ["latin"],
  weight: "400",
  variable: "--roboto-font",
});

const kanit = Kanit({
  subsets: ["latin"],
  weight: "400",
  variable: "--kanit-font",
});

const Home: NextPage = () => {
  const [menuOpen, setMenuOpen] = useState(false);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${kanit.variable} ${roboto.variable}`}>
        <Nav setMenuOpen={setMenuOpen} />
        <div className="flex h-[calc(100vh-_82.67px)] overflow-hidden">
          <LeftTab menuOpen={menuOpen} />
          <div className="grid items-start px-2 pt-10 sm:py-10">
            <Hero />
          </div>
          {/* <NewsTab /> */}
        </div>
      </main>
    </>
  );
};

export default Home;
